FROM node:20 AS metamodeling-client

RUN echo "Building the Docker image..."

RUN mkdir -p /usr/src/app/shared/mmar/mmar-metamodeling-client \
    /usr/src/app/shared/mmar/mmar-global-data-structure

COPY scripts/start-metamodeling-client.sh /usr/src/app/start-metamodeling-client.sh
RUN chmod +x /usr/src/app/start-metamodeling-client.sh

COPY scripts/npm-installation-metamodeling-client.sh /usr/src/app/npm-installation-metamodeling-client.sh
RUN chmod +x /usr/src/app/npm-installation-metamodeling-client.sh

COPY scripts/start-node-metamodeling-client.sh /usr/src/app/start-node-metamodeling-client.sh
RUN chmod +x /usr/src/app/start-node-metamodeling-client.sh

COPY conf /usr/src/app/mmar-config-files

CMD ["/usr/src/app/start-metamodeling-client.sh"]
