FROM node:20 AS modeling-client

RUN echo "Building the Docker image..."

RUN mkdir -p /usr/src/app/shared/mmar/mmar-modeling-client \
    /usr/src/app/shared/mmar/mmar-global-data-structure

COPY scripts/start-modeling-client.sh /usr/src/app/start-modeling-client.sh
RUN chmod +x /usr/src/app/start-modeling-client.sh

COPY scripts/npm-installation-modeling-client.sh /usr/src/app/npm-installation-modeling-client.sh
RUN chmod +x /usr/src/app/npm-installation-modeling-client.sh

COPY scripts/start-node-modeling-client.sh /usr/src/app/start-node-modeling-client.sh
RUN chmod +x /usr/src/app/start-node-modeling-client.sh

COPY conf /usr/src/app/mmar-config-files

CMD ["/usr/src/app/start-modeling-client.sh"]
