FROM node:20 AS metamodeling-react

RUN echo "Building the Docker image..."

RUN mkdir -p /usr/src/app/shared/mmar/mmar-metamodeling-client-react \
    /usr/src/app/shared/mmar/mmar-global-data-structure

COPY scripts/start-metamodeling-client-react.sh /usr/src/app/start-metamodeling-client-react.sh
RUN chmod +x /usr/src/app/start-metamodeling-client-react.sh

COPY scripts/npm-installation-metamodeling-client-react.sh /usr/src/app/npm-installation-metamodeling-client-react.sh
RUN chmod +x /usr/src/app/npm-installation-metamodeling-client-react.sh

COPY scripts/start-node-metamodeling-client-react.sh /usr/src/app/start-node-metamodeling-client-react.sh
RUN chmod +x /usr/src/app/start-node-metamodeling-client-react.sh

COPY conf /usr/src/app/mmar-config-files

CMD ["/usr/src/app/start-metamodeling-client-react.sh"]
